-- Project: Online Book Store SQL Analysis
-- Description: SQL queries to analyze an online bookstore dataset.
-- Skills Used: Joins, Aggregations, Window Functions, CTE
-- Dataset Source: Dataset collected from a public GitHub repository.
-- Original Source: GitHub - https://github.com/SatishDhawale/SQL_Resume_Project
-- Note: The dataset was taken from GitHub, but all SQL queries and analysis were written by me for learning and practice purposes.

-----------------------------------------------------------------------------------------------------------------------------------

-- Create Database
CREATE DATABASE IF NOT EXISTS OnlineBooksStore;
USE OnlineBooksStore;

SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

-- Basic Questions:

-- 1. Display all books with their stock:

SELECT Book_ID , Title, Stock FROM Books;

-- 2. Retrieve all books in the "Biography" genre:

SELECT * FROM Books 
WHERE Genre = 'Biography';

-- 3. Find books published after the year 1950:

SELECT * FROM Books
WHERE Published_Year > 1950;

-- 4. List all the customers from the canada:

SELECT * FROM Customers 
WHERE Country = 'canada';

-- 5. Calculate the total number of orders placed:

SELECT COUNT(*) AS Total_Orders
FROM Orders;

-- 6. Show the top 3 most expensive books of "Fantasy" Genre:

SELECT * FROM books
WHERE Genre = 'Fantasy'
ORDER BY price DESC
LIMIT 3;

-- 7. Show all customers who ordered more than 1 quantity of a book:

SELECT * FROM Orders 
WHERE Quantity > 1;

-- 8. Retrieve the total stock of books available:

SELECT sum(Stock) as 'Total_Stock'
FROM books;


-- 9. Find the average price of books in the "Fantasy" genre:

SELECT ROUND(AVG(Price),2) AS Avg_Price_Book 
FROM Books 
WHERE Genre = 'Fantasy';

-- 10. Find the details of the most expensive book:

SELECT * FROM books 
ORDER BY price DESC
LIMIT 1;


-- 11. Calculate the total revenue generated from all orders:

SELECT ROUND(SUM(Total_Amount),2) AS Total_Revenue 
FROM orders;

-- 12. Find the book with the lowest stock:

SELECT * FROM Books 
order by Stock 
limit 1;

-- 13. Retrieve all orders where the total amount exceeds $20:

SELECT * FROM Orders
WHERE Total_Amount > 20;


-- 14. Show orders placed in november 2023:

SELECT * FROM Orders 
WHERE Order_Date BETWEEN '2023-11-01' AND '2023-11-30';

-- 15. Calculate the total quantity ordered for each book:

SELECT b.Book_ID,
       b.Title,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title;

-- 16. Display the books that have not been ordered yet:

SELECT b.Book_ID,
       b.Title
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
HAVING SUM(o.Quantity) IS NULL;

-- 17. Find the book with the highest total ordered quantity:

SELECT b.Book_ID,
       b.Title,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
ORDER BY Total_Ordered DESC
LIMIT 1;

-- Advance Questions:

-- 1. Retrieve the total number of books sold for each genre:

SELECT b.Genre, 
       SUM(o.Quantity) AS 'Total_Books_Sold'
FROM Orders o
JOIN Books b ON o.Book_ID = b.Book_ID
GROUP BY b.Genre;

-- 2. Display books whose remaining stock is less than 5:

SELECT b.Book_ID,
       b.Title,
       b.Stock - COALESCE(SUM(o.Quantity),0) AS Remaining_Stock
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock
HAVING Remaining_Stock < 5;

-- 3. Display oversold books (ordered quantity > stock):

	SELECT b.Book_ID,
       b.Title,
       b.Stock,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock
HAVING COALESCE(SUM(o.Quantity),0) > b.Stock;

-- 4. List customers who have placed at least 2 orderd:

SELECT c.Name, 
       c.Customer_ID, 
       COUNT(o.Order_ID) as Order_Count
FROM Orders o
JOIN Customers c ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Name
HAVING COUNT(o.Order_ID) >= 2;

-- 5. Find the most frequently ordered book:

SELECT b.Title, 
	   b.Book_ID, 
       COUNT(o.Order_ID) as Most_Ordered_Book
FROM Orders o
JOIN Books b ON b.Book_ID = o.Book_ID
GROUP BY b.Title, b.Book_ID
ORDER BY Most_Ordered_Book
DESC LIMIT 1;

-- 6. Find the total revenue generated by each book (Assume Books table has Price column):

SELECT b.Book_ID,
       b.Title,
       SUM(o.Quantity * b.Price) AS Total_Revenue
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title;

-- 7. Retrieve the total quantity of books sold by each author:

SELECT b.Author, 
	SUM(o.Quantity) AS Total_Sold_by_Author
FROM orders o
JOIN Books b ON b.Book_ID = o.Book_ID
GROUP BY b.Author
ORDER BY Total_Sold_by_Author DESC; 

-- 8. List the cities where customers who spent over $300 are located:

SELECT DISTINCT c.city, 
				SUM(o.Total_Amount) AS Total_Spent
FROM orders o
JOIN Customers c ON o.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.City
HAVING Total_Spent > 300
ORDER BY Total_Spent DESC;

-- 9. Find the top 3 best-selling books based on revenue:

SELECT b.Book_ID,
       b.Title,
       SUM(o.Quantity * b.Price) AS Total_Revenue
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
ORDER BY Total_Revenue DESC
LIMIT 3;

-- 10. Find the customer who spent the most on orders:

SELECT c.Name, 
       c.Customer_ID, 
       ROUND(SUM(o.Total_Amount),2) AS Total_Spent
FROM orders o
JOIN customers c ON c.customer_ID = o.Customer_ID
GROUP BY c.Name, c.Customer_ID
ORDER BY Total_Spent DESC
LIMIT 1;

-- 11. Calculate the percentage of stock sold for each book:
SELECT b.Book_ID,
       b.Title,
       ROUND((COALESCE(SUM(o.Quantity),0) / b.Stock) * 100,2) AS Percentage_Sold
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock;

-- 12. Calculate the stock remaining after fulfilling all orders:

SELECT b.Book_ID,
       b.Title,
       b.Stock AS Original_Stock,
       COALESCE(SUM(o.Quantity), 0) AS Total_Ordered,
       b.Stock - COALESCE(SUM(o.Quantity), 0) AS Remaining_Stock
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock;

-- 13. Find the total quantity sold for each book and rank them from highest to lowest sales:

SELECT b.Book_ID,
       b.Title,
       COALESCE(SUM(o.Quantity),0) AS Total_Sold,
       RANK() OVER (
           ORDER BY COALESCE(SUM(o.Quantity),0) DESC
       ) AS Sales_Rank
FROM Books b
LEFT JOIN Orders o 
ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title;

-- 14. Retrieve the most recent order for each customer:

SELECT *
FROM (
    SELECT o.*,
           ROW_NUMBER() OVER (
               PARTITION BY o.Customer_ID
               ORDER BY o.Order_Date DESC
           ) AS rn
    FROM Orders o
) t
WHERE rn = 1;

-- 15. Rank customers based on their total spending:

SELECT c.Customer_ID,
       c.Name,
       SUM(o.Total_Amount) AS Total_Spent,
       DENSE_RANK() OVER (
           ORDER BY SUM(o.Total_Amount) DESC
       ) AS Spending_Rank
FROM Customers c
JOIN Orders o 
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Name;

-- 16. Calculate daily sales and show the cumulative (running) total revenue:

SELECT Order_Date,
       SUM(Total_Amount) AS Daily_Sales,
       SUM(SUM(Total_Amount)) 
       OVER (ORDER BY Order_Date) AS Running_Total
FROM Orders
GROUP BY Order_Date;

-- 17. Compare each day’s sales with the previous day’s sales:

SELECT Order_Date,
       SUM(Total_Amount) AS Daily_Sales,
       LAG(SUM(Total_Amount)) 
       OVER (ORDER BY Order_Date) AS Previous_Day_Sales
FROM Orders
GROUP BY Order_Date;

-- 18. Display each order along with the next order amount:

SELECT Order_ID,
       Customer_ID,
       Total_Amount,
       LEAD(Total_Amount) 
       OVER (ORDER BY Order_Date) AS Next_Order_Amount
FROM Orders;

-- 19. Find the top 2 best-selling books in each genre:
       
SELECT *
FROM (
    SELECT b.Genre,
           b.Title,
           SUM(o.Quantity) AS Total_Sold,
           ROW_NUMBER() OVER (
               PARTITION BY b.genre
               ORDER BY SUM(o.Quantity) DESC
           ) AS rn
    FROM Books b
    JOIN Orders o 
    ON b.Book_ID = o.Book_ID
    GROUP BY b.genre, b.Title
) t
WHERE rn <= 2;

-- 20. Assign a sequential order number to each customer's orders based on order date:

SELECT Order_ID,
       Customer_ID,
       Order_Date,
       ROW_NUMBER() OVER (
           PARTITION BY Customer_ID
           ORDER BY Order_Date
       ) AS Order_Number
FROM Orders;

-- 21. Display each order along with the overall average order amount:

SELECT Order_ID,
       Customer_ID,
       Total_Amount,
       ROUND(AVG(Total_Amount) OVER (), 2) AS Avg_Order_Amount
FROM Orders;

-- 22. Calculate monthly sales and show the difference compared to the previous month:

SELECT Month,
       Monthly_Sales,
       ROUND(Monthly_Sales - LAG(Monthly_Sales) 
       OVER (ORDER BY Month),2) AS Sales_Difference
FROM (
    SELECT DATE_FORMAT(Order_Date, '%Y-%m') AS Month,
           ROUND(SUM(Total_Amount),2) AS Monthly_Sales
    FROM Orders
    GROUP BY DATE_FORMAT(Order_Date, '%Y-%m')
) t;

-- 23. Find the top spending customer in each country:

SELECT *
FROM (
    SELECT c.Country,
           c.Name,
           SUM(o.Total_Amount) AS Total_Spent,
           RANK() OVER(PARTITION BY c.Country ORDER BY SUM(o.Total_Amount) DESC) AS rnk
    FROM Customers c
    JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
    GROUP BY c.Country, c.Name
) t
WHERE rnk = 1;

-- 24. Using CTE to find total revenue per book:

WITH Book_Revenue AS (
    SELECT b.Book_ID,
           b.Title,
           SUM(o.Quantity * b.Price) AS Revenue
    FROM Books b
    JOIN Orders o
    ON b.Book_ID = o.Book_ID
    GROUP BY b.Book_ID, b.Title
)
SELECT *
FROM Book_Revenue
ORDER BY Revenue DESC;

-- 25. Find the books whose revenue is greater than the average revenue of all books:

WITH Book_Revenue AS (
    SELECT b.Book_ID,
           b.Title,
           SUM(o.Quantity * b.Price) AS Revenue
    FROM Books b
    JOIN Orders o
    ON b.Book_ID = o.Book_ID
    GROUP BY b.Book_ID, b.Title
)
SELECT *
FROM Book_Revenue
WHERE Revenue > (
    SELECT AVG(Revenue)
    FROM Book_Revenue
);

-- 26. Find the customers who placed the highest number of orders

WITH Customer_Orders AS (
    SELECT c.Customer_ID,
           c.Name,
           COUNT(o.Order_ID) AS Total_Orders
    FROM Customers c
    JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
    GROUP BY c.Customer_ID, c.Name
)
SELECT *
FROM Customer_Orders
ORDER BY Total_Orders DESC
LIMIT 3;

-- 27. Calculate the remaining stock using CTE:

WITH Ordered_Quantity AS (
    SELECT Book_ID,
           SUM(Quantity) AS Total_Ordered
    FROM Orders
    GROUP BY Book_ID
)
SELECT b.Book_ID,
       b.Title,
       b.Stock,
       COALESCE(o.Total_Ordered,0) AS Total_Ordered,
       b.Stock - COALESCE(o.Total_Ordered,0) AS Remaining_Stock
FROM Books b
LEFT JOIN Ordered_Quantity o
ON b.Book_ID = o.Book_ID;


-- Case Studies (Business Analysis)

-- Case Study 1: Identify Top 5 Customers by Spending
-- Find the top 5 customers who spent the most money on orders:

SELECT c.Customer_ID,
       c.Name,
       SUM(o.Total_Amount) AS Total_Spent
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Name
ORDER BY Total_Spent DESC
LIMIT 5;

-- Case Study 2: Find the Best Selling Genre
-- Identify which book genre has sold the highest number of books:

SELECT b.Genre,
       SUM(o.Quantity) AS Total_Books_Sold
FROM Books b
JOIN Orders o
ON b.Book_ID = o.Book_ID
GROUP BY b.Genre
ORDER BY Total_Books_Sold DESC;

-- Case Study 3: Identify Inactive Customers
-- Find customers who have never placed any orders:

SELECT c.Customer_ID,
       c.Name
FROM Customers c
LEFT JOIN Orders o
ON c.Customer_ID = o.Customer_ID
WHERE o.Order_ID IS NULL;

-- Case Study 4: Find Monthly Revenue Trend
-- Analyze the monthly revenue trend of the online bookstore:

SELECT DATE_FORMAT(Order_Date,'%Y-%m') AS Month,
       SUM(Total_Amount) AS Monthly_Revenue
FROM Orders
GROUP BY DATE_FORMAT(Order_Date,'%Y-%m')
ORDER BY Month;

-- Case Study 5: Identify Top 3 Best Selling Books
-- Find the top 3 books that generated the highest revenue:

SELECT b.Book_ID,
       b.Title,
       SUM(o.Quantity * b.Price) AS Total_Revenue
FROM Books b
JOIN Orders o
ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
ORDER BY Total_Revenue DESC
LIMIT 3;
