-- Create Database
CREATE DATABASE IF NOT EXISTS OnlineBooksStore;
USE OnlineBooksStore;

SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

-- Basic Questions:

-- 1. Display all books with their stock:

SELECT Book_ID , Title, Stock FROM Books;

-- 2. Retrieve all books in the "Biography" genre:

SELECT * FROM Books 
WHERE Genre = 'Biography';

-- 3. Find books published after the year 1950:

SELECT * FROM Books
WHERE Published_Year > 1950;

-- 4. List all the customers from the canada:

SELECT * FROM Customers 
WHERE Country = 'Israel';

-- 5. Calculate the total number of orders placed:

SELECT COUNT(*) AS Total_Orders
FROM Orders;

-- 6. Calculate the total quantity ordered for each book:

SELECT b.Book_ID,
       b.Title,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title;

-- 7. Show orders placed in november 2023:

SELECT * FROM Orders 
WHERE Order_Date BETWEEN "2023-11-01" AND "2023-11-30";

-- 8. Display the books that have not been ordered yet:

SELECT b.Book_ID,
       b.Title
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
HAVING SUM(o.Quantity) IS NULL;

-- 9. Find the book with the highest total ordered quantity:

SELECT b.Book_ID,
       b.Title,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
ORDER BY Total_Ordered DESC
LIMIT 1;

-- 10. Retrieve the total stock of books available:

SELECT sum(Stock) as "Total_Stock"
FROM books;

-- 11. Find the details of the most expensive book:

SELECT * FROM books 
ORDER BY price DESC
LIMIT 1;

-- 12. Show all customers who ordered more than 1 quantity of a book:

SELECT * FROM Orders 
WHERE Quantity > 1;

-- 13. Retrieve all orders where the total amount exceeds $20:

SELECT * FROM Orders
WHERE Total_Amount > 20;

-- 14. List all genres available in the books table:

SELECT DISTINCT genre FROM Books;

-- 15. Find the book with the lowest stock:

SELECT * FROM Books 
order by Stock 
limit 1;

-- 16. Calculate the total revenue generated from all orders:

SELECT ROUND(SUM(Total_Amount),2) AS Total_Revenue 
FROM orders;

-- Advance Questions:

-- 1. Retrieve the total number of books sold for each genre:

SELECT b.Genre, 
       SUM(o.Quantity) as "Total_Books_Sold"
FROM Orders o
JOIN Books b ON o.Book_ID = b.Book_ID
GROUP BY b.Genre;

-- 2. Display books whose remaining stock is less than 5:

SELECT b.Book_ID,
       b.Title,
       b.Stock - COALESCE(SUM(o.Quantity),0) AS Remaining_Stock
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock
HAVING Remaining_Stock < 5;

-- 3. Display oversold books (ordered quantity > stock):

SELECT b.Book_ID,
       b.Title,
       b.Stock,
       COALESCE(SUM(o.Quantity),0) AS Total_Ordered
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock
HAVING COALESCE(SUM(o.Quantity),0) > b.Stock;

-- 4. Find the average price of books in the "Fantasy" genre:

SELECT ROUND(AVG(Price),2) AS Avg_Price_Book 
FROM Books 
WHERE Genre = "Fantasy";

-- 5. List customers who have placed at least 2 orderd:

SELECT c.Name, 
       c.Customer_ID, 
       COUNT(o.Order_ID) as Order_Count
FROM Orders o
JOIN Customers c ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Name
HAVING COUNT(o.Order_ID) >= 2;

-- 6. Find the most frequently ordered book:

SELECT b.Title, 
	   b.Book_ID, 
       COUNT(o.Order_ID) as Most_Ordered_Book
FROM Orders o
JOIN Books b ON b.Book_ID = o.Book_ID
GROUP BY b.Title, b.Book_ID
ORDER BY Most_Ordered_Book
DESC LIMIT 1;

-- 7. Show the top 3 most expensive books of "Fantasy" Genre:

SELECT * FROM books
WHERE Genre = "Fantasy"
ORDER BY price DESC
LIMIT 3;

-- 8. Find the total revenue generated by each book (Assume Books table has Price column):

SELECT b.Book_ID,
       b.Title,
       SUM(o.Quantity * b.Price) AS Total_Revenue
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title;

-- 9. Retrieve the total quantity of books sold by each author:

SELECT b.Author, 
	SUM(o.Quantity) AS Total_Sold_by_Author
FROM orders o
JOIN Books b ON b.Book_ID = o.Book_ID
GROUP BY b.Author
ORDER BY Total_Sold_by_Author DESC; 

-- 10. List the cities where customers who spent over $300 are located:

SELECT DISTINCT c.city, 
				SUM(o.Total_Amount) AS Total_Spent
FROM orders o
JOIN Customers c ON o.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.City
HAVING Total_Spent > 300
ORDER BY Total_Spent DESC;

-- 11. Find the top 3 best-selling books based on revenue:

SELECT b.Book_ID,
       b.Title,
       SUM(o.Quantity * b.Price) AS Total_Revenue
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title
ORDER BY Total_Revenue DESC
LIMIT 3;

-- 12. Find the customer who spent the most on orders:

SELECT c.Name, 
       c.Customer_ID, 
       ROUND(SUM(o.Total_Amount),2) AS Total_Spent
FROM orders o
JOIN customers c ON c.customer_ID = o.Customer_ID
GROUP BY c.Name, c.Customer_ID
ORDER BY Total_Spent DESC
LIMIT 1;

-- 13. Calculate the percentage of stock sold for each book:
SELECT b.Book_ID,
       b.Title,
       ROUND((COALESCE(SUM(o.Quantity),0) / b.Stock) * 100,2) AS Percentage_Sold
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock;

-- 14. Calculate the stock remaining after fulfilling all orders:

SELECT b.Book_ID,
       b.Title,
       b.Stock AS Original_Stock,
       COALESCE(SUM(o.Quantity), 0) AS Total_Ordered,
       b.Stock - COALESCE(SUM(o.Quantity), 0) AS Remaining_Stock
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock;